spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: admin
      password: admin

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.blog.backend.entity

server:
  port: 3000
  servlet:
    context-path: /api

jwt:
  secret: your-secret-key-change-this-in-production
  expiration: 86400000 # 24 hours in milliseconds
  header: Authorization
